-- Supply chain analytics environment setup: warehouse, database, and schemas
-- Co-authored with CoCo
SELECT CURRENT_ROLE(), CURRENT_USER();
CREATE WAREHOUSE IF NOT EXISTS SUPPLY_CHAIN_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

SHOW WAREHOUSES LIKE 'SUPPLY_CHAIN_WH';

CREATE DATABASE IF NOT EXISTS SUPPLY_CHAIN_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ANALYTICS.RAW;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ANALYTICS.STAGING;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ANALYTICS.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS SUPPLY_CHAIN_ANALYTICS.MARTS;

USE WAREHOUSE SUPPLY_CHAIN_WH;
USE DATABASE SUPPLY_CHAIN_ANALYTICS;
USE SCHEMA RAW;

SELECT
    CURRENT_WAREHOUSE(),
    CURRENT_DATABASE(),
    CURRENT_SCHEMA();


SHOW SCHEMAS IN DATABASE SUPPLY_CHAIN_ANALYTICS;

SELECT
    CURRENT_DATABASE(),
    CURRENT_SCHEMA();

SHOW SCHEMAS IN DATABASE SUPPLY_CHAIN_ANALYTICS;

