USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SUPPLY_CHAIN_WH;
USE DATABASE SUPPLY_CHAIN_ANALYTICS;
USE SCHEMA RAW;


-- Table 1: Suppliers
CREATE OR REPLACE TABLE RAW_SUPPLIERS (
    ID VARCHAR,
    NAME VARCHAR,
    STREET_ADDRESS VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    ZIP VARCHAR,
    WEBSITE VARCHAR,
    CONTACT_NAME VARCHAR,
    CONTACT_EMAIL VARCHAR,
    CONTACT_PHONE VARCHAR
);


-- Table 2: Projects
CREATE OR REPLACE TABLE RAW_PROJECTS (
    ID VARCHAR,
    PROJECT_LEVEL VARCHAR,
    NAME VARCHAR
);


-- Table 3: Products
CREATE OR REPLACE TABLE RAW_PRODUCTS (
    ID VARCHAR,
    BOM_LEVEL VARCHAR,
    NAME VARCHAR,
    PROJECT_ID VARCHAR,
    REVISION VARCHAR,
    PHASE VARCHAR,
    DESCRIPTION VARCHAR,
    UNIT_OF_MEASURE VARCHAR,
    PROCUREMENT_TYPE VARCHAR,
    PART_OWNER VARCHAR,
    CREATION_DATE VARCHAR,
    MANUFACTURER_1 VARCHAR,
    MANUFACTURER_PART_NUMBER_1 VARCHAR,
    MANUFACTURER_PART_NAME_1 VARCHAR,
    MANUFACTURER_2 VARCHAR,
    MANUFACTURER_PART_NUMBER_2 VARCHAR,
    MANUFACTURER_PART_NAME_2 VARCHAR,
    VENDOR_1 VARCHAR,
    VENDOR_PART_NUMBER_1 VARCHAR,
    VENDOR_PART_NAME_1 VARCHAR,
    VENDOR_2 VARCHAR,
    VENDOR_PART_NUMBER_2 VARCHAR,
    VENDOR_PART_NAME_2 VARCHAR,
    SUPPLIER_ID VARCHAR
);


-- Verify that all three tables exist
SHOW TABLES IN SCHEMA SUPPLY_CHAIN_ANALYTICS.RAW;

DESCRIBE TABLE SUPPLY_CHAIN_ANALYTICS.RAW.RAW_PRODUCTS;

SELECT COUNT(*) AS SUPPLIER_COUNT
FROM SUPPLY_CHAIN_ANALYTICS.RAW.RAW_SUPPLIERS;

SELECT COUNT(*) AS PRODUCT_COUNT
FROM SUPPLY_CHAIN_ANALYTICS.RAW.RAW_PRODUCTS;

SELECT
    ID,
    BOM_LEVEL,
    NAME,
    PROJECT_ID,
    REVISION,
    PROCUREMENT_TYPE,
    SUPPLIER_ID
FROM SUPPLY_CHAIN_ANALYTICS.RAW.RAW_PRODUCTS
LIMIT 10;

SELECT
    ID,
    NAME,
    SUPPLIER_ID
FROM SUPPLY_CHAIN_ANALYTICS.RAW.RAW_PRODUCTS
WHERE SUPPLIER_ID LIKE '%;%'
LIMIT 10;