USE ROLE ACCOUNTADMIN;
USE WAREHOUSE SUPPLY_CHAIN_WH;
USE DATABASE SUPPLY_CHAIN_ANALYTICS;
USE SCHEMA RAW;


-- One row per purchase order
CREATE OR REPLACE TABLE RAW_PURCHASE_ORDERS (
    PURCHASE_ORDER_ID VARCHAR,
    SUPPLIER_ID VARCHAR,
    ORDER_DATE DATE,
    BUYER_NAME VARCHAR,
    ORDER_STATUS VARCHAR
);


-- One row per product within a purchase order
CREATE OR REPLACE TABLE RAW_PURCHASE_ORDER_LINES (
    PURCHASE_ORDER_LINE_ID VARCHAR,
    PURCHASE_ORDER_ID VARCHAR,
    LINE_NUMBER INTEGER,
    PRODUCT_ID VARCHAR,
    ORDERED_QUANTITY INTEGER,
    UNIT_PRICE NUMBER(12, 2),
    STANDARD_UNIT_PRICE NUMBER(12, 2),
    PROMISED_DELIVERY_DATE DATE,
    ACTUAL_DELIVERY_DATE DATE,
    RECEIVED_QUANTITY INTEGER
);


-- One row per quality inspection
CREATE OR REPLACE TABLE RAW_INSPECTIONS (
    INSPECTION_ID VARCHAR,
    PURCHASE_ORDER_LINE_ID VARCHAR,
    INSPECTION_DATE DATE,
    INSPECTED_QUANTITY INTEGER,
    REJECTED_QUANTITY INTEGER,
    DEFECT_CATEGORY VARCHAR
);


-- Verify the tables
SHOW TABLES IN SCHEMA SUPPLY_CHAIN_ANALYTICS.RAW;
DESCRIBE TABLE RAW_INSPECTIONS;
SELECT
    (SELECT COUNT(*) FROM RAW_PURCHASE_ORDERS) AS PURCHASE_ORDERS,
    (SELECT COUNT(*) FROM RAW_PURCHASE_ORDER_LINES) AS ORDER_LINES,
    (SELECT COUNT(*) FROM RAW_INSPECTIONS) AS INSPECTIONS;